<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "annuaire_matthias_rodier"
 *
 * Auto generated by Extension Builder 2017-07-10
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'Annuaire MRodier',
    'description' => 'A little test to implement an extension to typo3',
    'category' => 'plugin',
    'author' => 'Matthias Rodier',
    'author_email' => 'matthias.rodier@etu.u-bordeaux.fr',
    'state' => 'alpha',
    'internal' => '',
    'uploadfolder' => '1',
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '1.0.0',
    'constraints' => [
        'depends' => [
            'typo3' => '7.6.0-7.6.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
